// Code generated by MCHP Chatbot

#include "mcc_generated_files/system/system.h"
#include "mcc_generated_files/timer/tmr0.h"
#include "hc164.h"

// Variables de control
static volatile uint8_t columna_actual = 0; // Columna del mensaje
static volatile uint8_t bit_corrimiento = 0; // Bit siendo corrido (0 a 24)
static volatile uint8_t clk_switch = 0; // Dato actual a enviar al 74HC164
static volatile uint8_t rotacion_pendiente = 0;
// Fuente 5x8 almacenada por columnas (bit 0 arriba, bit 7 abajo)
const uint8_t font5x8[][5] = {
    {0x00,0x00,0x00,0x00,0x00}, // Espacio
    {0xFF,0x18,0x18,0x18,0xFF}, // H
    {0x7E,0x81,0x81,0x81,0x7E}, // O
    {0xFF,0x80,0x80,0x80,0x80}, // L
    {0xFE,0x91,0x91,0x91,0xFE}, // A
    {0x00,0x00,0x00,0x00,0x00}, // Espacio
    {0xFF,0x06,0x18,0x06,0xFF}, // M
    {0x7F,0x80,0x80,0x80,0x7F}, // U
    {0xFF,0x06,0x18,0x60,0xFF}, // N
    {0xFF,0x81,0x81,0x66,0x3C}, // D
    {0x7E,0x81,0x81,0x81,0x7E}, // O
};

// Indices para " HOLA MUNDO "
const uint8_t mensaje[] = {0,1,2,3,4,5,6,7,8,9,10,0};
#define LETRAS (sizeof(mensaje)/sizeof(mensaje[0]))
#define COLS_TOTAL (LETRAS*5 + LETRAS - 1)

// Buffer de columnas para scroll
uint8_t buffer[COLS_TOTAL] = {0};

void generar_buffer_mensaje(void){
    uint8_t idx=0;
    for(uint8_t l=0; l<LETRAS; l++) {
        for(uint8_t c=0; c<5; c++) {
            buffer[idx++] = (uint8_t)(font5x8[mensaje[l]][c] ^ 0xFF);
        }
        if(l + 1 < LETRAS) {
            buffer[idx++] = 0xFF;
        }
    }
}

static void desplazar_buffer(void) {
    uint8_t primera_columna = buffer[0];
    for(uint8_t i=0; i<COLS_TOTAL-1; i++) {
        buffer[i] = buffer[i+1];
    }
    buffer[COLS_TOTAL-1] = primera_columna;
}

// Interrupción de TMR0: cada vez manda UN bit del dato actual en AB, genera pulso de CLK
void TMR0_CustomISR(void) {

    // Pulso de clock
    if (clk_switch == 0) {
        CLK_SetHigh();
        if(bit_corrimiento ==0)
            AB_SetHigh(); // Enviar el bit actual
        else
            AB_SetLow(); // Enviar el bit actual
        clk_switch = 1;
        
    } else {
        CLK_SetLow();
        bit_corrimiento++;
        if(bit_corrimiento >= 25) {
            bit_corrimiento = 0; // Reinicia el corrimiento
            rotacion_pendiente = 1;
        }
        clk_switch = 0;
    }
    columna_actual++;
    if(columna_actual >= COLS_TOTAL) {
        columna_actual = 0; // Reinicia la columna
    }
}

int main(void) { 
    SYSTEM_Initialize();
    hc164_init();
    generar_buffer_mensaje();

    TMR0_OverflowCallbackRegister(TMR0_CustomISR);
    TMR0_TMRInterruptEnable();
    INTCONbits.PEIE = 1;
    INTCONbits.GIE = 1;

    while(1) {
        if(rotacion_pendiente != 0) {
            rotacion_pendiente = 0;
            desplazar_buffer();
        }

        if(clk_switch == 0)
            LATB = buffer[bit_corrimiento]; // Para debug, ver la columna actual en PORTB
            
    }
}


